specVersion: 1.0.0
name: bifrost-subql-starter
version: 0.0.5
runner:
  node:
    name: '@subql/node'
    version: '*'
  query:
    name: '@subql/query'
    version: '*'
description: This project can be use as a starting point for Bifrost network.
repository: 'https://github.com/subquery/bifrost-subql-starter'
schema:
  file: ./schema.graphql
network:
  chainId: '0x9f28c6a68e0fc9646eff64935684f6eeeece527e37bbe1f213d22caa1d9d6bed'
  endpoint: 'wss://bifrost-parachain.api.onfinality.io/public-ws'
  dictionary: 'https://api.subquery.network/sq/subquery/bifrost-parachain-dictionary'
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Deposit
        - handler: handleCall
          kind: substrate/CallHandler
